# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Demos
  demands:
    - agent.name -equals mydockeragent

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/pipeline/hello-world/hello-world.csproj'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/pipeline/db-tests/db-tests.csproj'
    testRunTitle: 'Database tests'