# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Demos

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/pipeline/db-tests/db-tests.csproj'
    testRunTitle: 'Database tests'
  env:
    SA_PASSWORD: $(SA_PASSWORD)